# Generated by Django 2.2.11 on 2020-03-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(db_column='ISBN', max_length=30, primary_key=True, serialize=False)),
                ('book_name', models.CharField(db_column='Book_Name', max_length=200)),
                ('edition', models.IntegerField(db_column='Edition')),
                ('author', models.CharField(db_column='Author', max_length=100)),
                ('genre', models.CharField(blank=True, db_column='Genre', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('date_of_request', models.DateField(db_column='Date_of_Request')),
                ('request_message', models.CharField(blank=True, db_column='Request_Message', max_length=100, null=True)),
                ('request_id', models.AutoField(db_column='Request_ID', primary_key=True, serialize=False)),
                ('time_of_request', models.IntegerField()),
                ('borrow_time_duration', models.IntegerField()),
                ('completion_flag', models.IntegerField()),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(db_column='User_ID', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('email_address', models.CharField(db_column='Email_Address', max_length=30)),
                ('house_number', models.CharField(blank=True, db_column='House_Number', max_length=10, null=True)),
                ('street', models.CharField(db_column='Street', max_length=20)),
                ('locality', models.CharField(db_column='Locality', max_length=30)),
                ('postal_code', models.DecimalField(db_column='Postal_Code', decimal_places=0, max_digits=6)),
                ('landmark', models.CharField(blank=True, db_column='Landmark', max_length=30, null=True)),
                ('city', models.CharField(db_column='City', max_length=30)),
                ('state', models.CharField(db_column='State', max_length=30)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('phone_number', models.DecimalField(db_column='Phone_Number', decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'User_Phone_Number',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('rating', models.IntegerField(db_column='Rating')),
                ('review', models.CharField(blank=True, db_column='Review', max_length=5000, null=True)),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bookbayapp.User')),
            ],
            options={
                'db_table': 'Book_Review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bookbayapp.User')),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginCredential',
            fields=[
                ('password', models.CharField(db_column='Password', max_length=30)),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bookbayapp.User')),
            ],
            options={
                'db_table': 'Login_Credential',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyBooks',
            fields=[
                ('repayment_policy', models.CharField(db_column='Repayment_Policy', max_length=1000)),
                ('availability', models.IntegerField(db_column='Availability')),
                ('other_specifications', models.CharField(blank=True, db_column='Other_Specifications', max_length=1000, null=True)),
                ('security_money_of_book', models.IntegerField(db_column='Security_Money_of_Book')),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bookbayapp.User')),
            ],
            options={
                'db_table': 'My_Books',
                'managed': False,
            },
        ),
    ]
