# Generated by Django 3.0.4 on 2020-03-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='bookreview',
            table='book_review',
        ),
        migrations.AlterModelTable(
            name='logincredential',
            table='login_credential',
        ),
        migrations.AlterModelTable(
            name='mybooks',
            table='my_books',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userphonenumber',
            table='user_phone_number',
        ),
    ]
